{{- if .Values.serviceAccount.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubiya-operator.fullname" . }}-copy-secret
  namespace: {{ .Values.openfaasNamespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      containers:
      - name: secret-copier
        image: bitnami/kubectl
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          if [ "{{ .Values.openfaasNamespace }}" != "{{ .Release.Namespace }}" ]; then
            echo "Namespaces differ, copying secret..."
            kubectl get secret {{ .Values.openfaas.basicAuthSecretName }} --namespace={{ .Values.openfaasNamespace }} -o yaml |
            yq e 'del(.metadata.creationTimestamp, .metadata.resourceVersion, .metadata.uid, .metadata.selfLink, .metadata.namespace)' - |
            kubectl apply --namespace={{ .Release.Namespace }} -f -
          else
            echo "Secret is in the correct namespace, no action needed."
          fi
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
{{- end }}
