{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "kubiya-operator-sa" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
